cmake .. \
 -DMNN_LOW_MEMORY=true -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true -DMNN_BUILD_LLM=true -DMNN_SUPPORT_TRANSFORMER_FUSE=true \
 -DCMAKE_OSX_ARCHITECTURES=arm64 \
 -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_TORCH=ON \
 -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON -DMNN_BUILD_DIFFUSION=ON \
 -DMNN_BUILD_TOOL=ON \
 -DMNN_BUILD_QUANTOOLS=ON \
 -DMNN_BUILD_EXAMPLES=ON \
 -DCMAKE_POLICY_VERSION_MINIMUM=3.5
